name: Page Publish

on: 
  repository_dispatch:
    types:
      - resource-published

jobs:
  build-coveo:
    runs-on: ubuntu-latest
    steps:
      - name: Extract language
        id: get_language
        run: |
          path="${{ github.event.client_payload.path }}"
          echo "Path: $path"  # Debugging statement
          language=$(echo "$path" | awk -F '/' '{print $2}')
          echo "Language extracted: $language"  # Debugging statement
          echo "::set-output name=language::$language"

      - uses: actions/checkout@v3
      - name: Get Repository Information
        id: get_repo_info
        run: |
          repo_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }})
          repo_html_url=$(echo "$repo_info" | jq -r '.html_url')
          echo "::set-output name=repo_html_url::$repo_html_url"
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Ensure version is compatible with the script
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Generate Coveo Index
        working-directory: ./coveo
        run: |
          node generate-coveo-index.js \
            --language ${{ steps.get_language.outputs.language }} \
            --domain "${{ steps.get_repo_info.outputs.repo_html_url }}" \
            > coveo_${{ steps.get_language.outputs.language }}.xml
          
          # Check if the file exists or has been modified
          if [ -f ./coveo_${{ steps.get_language.outputs.language }}.xml ]; then
            echo "File exists"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add ./coveo_${{ steps.get_language.outputs.language }}.xml
            git commit -m "Update generated coveo_${{ steps.get_language.outputs.language }}.xml file"
            git push
          else
            echo "File does not exist"
            exit 1
          fi
